// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/home/calculators': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/home/calculators.get').default>>>>
    }
    '/api/home/hero': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/home/hero.get').default>>>>
    }
    '/api/home/offers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/home/offers.get').default>>>>
    }
    '/api/home/tokens': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/home/tokens.get').default>>>>
    }
    '/api/service-categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/service-categories.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}