// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/10/2025, 9:50:40 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/plugins/**/*.{js,ts,mjs}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/composables/**/*.{js,ts,mjs}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/utils/**/*.{js,ts,mjs}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamadalhalabi/development/pincode-frontend-nuxt4/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;